### PR TITLE
Correctly refer to the error type?

### PR DESCRIPTION
**Pull request by ByteJunk**
Hey! Using your project to familiarize myself with rest in typescript. Shouldn't the error be addressed differently here?

### CODE REVIEW

**Comment by wata** [comment]
@ByteJunk Thanks for the PR!

The `error` on line 60 is not found, resulting in a compile error, right?

**Comment by ByteJunk** [comment]
Hi @wata! 
There's no actual errors, compiling or running, but I get a warning in the IDE with this code:
`   let result = RestClient.send(request);
    if(!result.ok) {
        handleError(result.error)
    }`

Here I'll get "_Property 'error' does not exist on type '{ ok: true; value: IResponse<IQueryResponse>; }'_".

Am I misunderstanding the usage?

Thanks!

**Comment by wata** [comment]
I still do not know where the `error` on line 60 is in your code 😂 

And I get a compile error in my environment
```sh
src/RestClient.ts:60:9 - error TS2552: Cannot find name 'error'. Did you mean 'Error'?

60     if (error) {
           ~~~~~
```

Could you elaborate on the purpose of this PR? Is it a variable naming issue?

**Comment by ByteJunk** [comment]
Hey @wata! 

I'm sorry, I forgot to also rename the variable name in line 60, it should be "interceptedError". Renaming this variable is just for clarity purposes.

The issue that the PR is meant to solve is with line 61: my understanding is that the returned object should include an "error:" property, or the typechecking will show a warning when trying to access the result.error property. 

Am I incorrect?

Thanks!

**Comment by wata** [comment]
@ByteJunk Thanks for explaining.

If the variable name and the object property name are the same, it can be omitted -- [Shorthand property names](https://ui.dev/shorthand-properties)
`{ ok: false, error: error }` => `{ ok: false, error }`

You will see by looking at the compiled `RestClient.js` that accessing `result.error` is not a problem.
```js
    Request.prototype.response = function (httpResponse) {
        var contents = httpResponse.getContentText();
        var parsedObject = contents.length > 0 ? JSON.parse(contents) : {};
        var error = this.intercept(parsedObject, httpResponse);
        if (error) {
            return { ok: false, error: error };
        }
        var response = {
            statusCode: httpResponse.getResponseCode(),
            object: parsedObject,
            headers: httpResponse.getAllHeaders()
        };
        return { ok: true, value: response };
    };
```

**Pull request closed without merging**
